apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-crisis-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crisis-detection
  template:
    metadata:
      labels:
        app: crisis-detection
    spec:
      containers:
      - name: model-service
        image: crisis-detection:latest
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: MODEL_VERSION
          value: "v1"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
