learning_rate: 1e-4
max_epochs: 20
batch_size: 8
gradient_clip_val: 1.0
early_stopping_patience: 5
checkpoint:
  monitor: 'train_loss'
  mode: 'min'
  save_top_k: 1
  filename: 'best-model-{epoch:02d}-{train_loss:.3f}'
