defaults:
  - model: config
  - training: config
  - _self_

checkpoint_path: null

data:
  max_seq_length: 4096
  max_documents: 1000
  num_workers: 4

wandb:
  project: "financial-crisis-lite"
  tags: ["production"]
